enum PersonalLoanServiceErrorCodes {
  unable_to_select_offer,
  on_select_03_error,
  aadhar_kyc_failed,
  on_init_01_error,
  on_init_02_error,
  repayment_setup_failed,
  on_init_03_error,
  loan_agreement_failed,
  on_confirm_01_failed,
  on_update_01_failed,
  generate_monitoring_consent_failed,
  monitoring_consent_verification_failed,
  loan_sanction_failed,
  request_timeout,
}