name: blocsol_loan_application
description: "All in one loan application on ONDC FS"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  awesome_snackbar_content: ^0.1.3
  dio: ^5.5.0+1
  dropdown_button2: ^2.3.9
  eventflux: ^2.1.0
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  flutter_advanced_switch: ^3.1.0
  flutter_countdown_timer: ^4.1.0
  flutter_holo_date_picker: ^1.1.3
  flutter_inappwebview: ^6.0.0
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.2.2
  freezed_annotation: ^2.4.4
  go_router: ^14.2.1
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  jwt_decoder: ^2.0.1
  logger: ^2.4.0
  lottie: ^3.1.2
  percent_indicator: ^4.2.3
  permission_handler: ^11.3.1
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  sentry_flutter: ^8.5.0
  shared_preferences: ^2.2.3
  sleek_circular_slider: ^2.0.1
  sms_autofill: ^2.4.0
  string_similarity: ^2.0.0
  swipe_refresh: ^1.1.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.0
  freezed: ^2.5.2
  change_app_package_name: ^1.3.0

flutter:
  uses-material-design: true
  assets:
    # Image Assets
    - assets/images/lender_logos/bank.png
    - assets/images/lender_logos/sidbi.png
    - assets/images/lender_logos/icici.png
    - assets/images/lender_logos/hdfc.png
    - assets/images/lender_logos/kotak.png
    - assets/images/lender_logos/axis.png
    - assets/images/lender_logos/central-bank.png
    - assets/images/lender_logos/idbi.png
    - assets/images/lender_logos/idfc.jpeg
    - assets/images/lender_logos/indusind.png
    - assets/images/lender_logos/punjab-national.png
    - assets/images/lender_logos/uco.png
    - assets/images/lender_logos/union.png
    - assets/images/lender_logos/dmi.png

    - assets/images/aa_logos/anumati.png
    - assets/images/aa_logos/finvu.png
    - assets/images/aa_logos/onemoney.png
    - assets/images/aa_logos/sahamati.png
    - assets/images/aa_logos/sahamati_certified.png
    - assets/images/aa_logos/account_aggregator_process.png

    - assets/images/invoice_loan/bottom_nav_bar/home_active.png
    - assets/images/invoice_loan/bottom_nav_bar/home_inactive.png
    - assets/images/invoice_loan/bottom_nav_bar/invoices_active.png
    - assets/images/invoice_loan/bottom_nav_bar/invoices_inactive.png
    - assets/images/invoice_loan/bottom_nav_bar/loans_active.png
    - assets/images/invoice_loan/bottom_nav_bar/loans_inactive.png
    - assets/images/invoice_loan/bottom_nav_bar/profile_active.png
    - assets/images/invoice_loan/bottom_nav_bar/profile_inactive.png

    # Permissions
    - assets/images/invoice_loan/permissions/p1.png
    - assets/images/invoice_loan/permissions/p2.png
    - assets/images/invoice_loan/permissions/p3.png

    # Dashboard
    - assets/images/invoice_loan/dashboard/header/user_icon.png

    # Profile
    - assets/images/invoice_loan/profile/office.png
    - assets/images/invoice_loan/profile/settings.png

    # Liabilities
    - assets/images/invoice_loan/liabilities/background.png

    # Invoice New Loan Request
    - assets/images/invoice_loan/new_loan_request/invoice.png

    # Animation Assets
    - assets/animations/loading_spinner.json
    - assets/animations/downloading_data.json
    - assets/animations/submitting_details.json
    - assets/animations/verified.json
    - assets/animations/error.json
    - assets/animations/processing_form.json
    - assets/animations/money_growth_person.json
    - assets/animations/invoices.json
    - assets/animations/create_profile.json
    - assets/animations/hourglass.json
    - assets/animations/submitting_invoices.json
    - assets/animations/filing_invoice_forms.json
    - assets/animations/clock.json
    - assets/animations/404.json
    - assets/animations/searching_data.json
    - assets/animations/invoice_offer_not_found.json
    - assets/animations/downloading_new_data.json
    - assets/animations/fetching_data.json
    - assets/animations/under_construction.json
    - assets/animations/empty.json

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
