// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVtP7WP_Lja4fOgDu6yiy7PxnFHVaimNE',
    appId: '1:397572321624:android:46d6a28833640612b0f52d',
    messagingSenderId: '397572321624',
    projectId: 'financial-services-55edc',
    storageBucket: 'financial-services-55edc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC72hEpZdQQJPOEFxYwRXXVf-_cTAbi1yM',
    appId: '1:397572321624:ios:9f2bda482a78f5b1b0f52d',
    messagingSenderId: '397572321624',
    projectId: 'financial-services-55edc',
    storageBucket: 'financial-services-55edc.appspot.com',
    androidClientId: '397572321624-499l7dsh05fl40h5jgon8iqusdf1oet8.apps.googleusercontent.com',
    iosClientId: '397572321624-4uendgt2av0665noeltcpa7gm0eron20.apps.googleusercontent.com',
    iosBundleId: 'blocsol.credit.app',
  );

}