// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh0XYwFUEY0xLlZ4L2BG_b4VeWT9ip7AM',
    appId: '1:322285078885:android:c197e78fd06f790021398c',
    messagingSenderId: '322285078885',
    projectId: 'credit-app-a24e3',
    storageBucket: 'credit-app-a24e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeG1NvasV7-hYpRgsESvRmUnuDwABLQ1o',
    appId: '1:322285078885:ios:28056bde5ed12cd821398c',
    messagingSenderId: '322285078885',
    projectId: 'credit-app-a24e3',
    storageBucket: 'credit-app-a24e3.appspot.com',
    androidClientId: '322285078885-qfad7mr7e8hbvnd754m91vl7kg67lif9.apps.googleusercontent.com',
    iosClientId: '322285078885-kq8ne6lursts08dnosg375mkloo4p6q9.apps.googleusercontent.com',
    iosBundleId: 'blocsol.credit.app',
  );

}